# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            iequalsi
tagline:          '(i=i)'
description:      "Well, the way they make shows is, they make one show. That show's called a pilot."
url:              https://iequalsi.com
baseurl:          /

author:
  name:           'Matthew Jording'
  url:            https://twitter.com/mjording

# Plugins
  gems:           [jekyll-paginate]

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mjording/mjording.github.io
